### ISSUE TITLE
Add Terms and Conditions Link in Footer

### ISSUE THREAD

**Issue by gayankalhara** [gayankalhara/reallybadgifts-coming-soon#1]

**Comment by Captain-DarkO** [comment]
okay

**Comment by theprogramsam** [comment]
I gotcha

**Comment by gayankalhara** [comment]
Please create a new page and put these contents and add the link in bottom. That's all! Thanks guys...!

https://drive.google.com/open?id=0B31JI7Qi3tYock9wOXI0ZzZpeEU

**Comment by Captain-DarkO** [comment]
on it..
