### ISSUE TITLE
Top Text and Image is not centered properly

### ISSUE THREAD

**Issue by gayankalhara** [gayankalhara/reallybadgifts-coming-soon#15]
/thanks-for-signing-up/index.html

![image](https://user-images.githubusercontent.com/8076584/32132949-40047588-bbeb-11e7-9969-76b05dc48fb8.png)

/success/index.html

![image](https://user-images.githubusercontent.com/8076584/32132947-363fbf76-bbeb-11e7-91dd-8ddd7c020eab.png)

**Comment by takejaw6** [comment]
tos.html
<img width="906" alt="screen shot 2017-10-28 at 02 38 57" src="https://user-images.githubusercontent.com/10733485/32133256-3d082030-bb89-11e7-8352-287649c8d0ca.png">
I have a question to ask. Does this look as you intended?

**Comment by takejaw6** [comment]
Done https://github.com/gayankalhara/reallybadgifts-coming-soon/pull/17

**Comment by gayankalhara** [comment]
@takejaw6 
Actually tos.html changed a bit. The 'coming soon' text is no longer there. Please check the latest commits.

And thank you very much for fixing #17. I'll check and merge now!

**Comment by takejaw6** [comment]
Done https://github.com/gayankalhara/reallybadgifts-coming-soon/pull/20

**Comment by gayankalhara** [comment]
Thanks @takejaw6
