### ISSUE TITLE
Edit email optin success page

### ISSUE THREAD

**Issue by gayankalhara** [gayankalhara/reallybadgifts-coming-soon#2]
![rbg landing page opt in success 3](https://user-images.githubusercontent.com/8076584/32116674-42326612-bb69-11e7-9615-159e519bc38a.png)

**Comment by gayankalhara** [comment]
Here's the PNG for this...

![char-3](https://user-images.githubusercontent.com/8076584/32120349-d5fa4110-bb75-11e7-8f59-fafde3b51a3d.png)

**Comment by tutorialdrive** [comment]
Okay, Contributing on it. Will change some style of success page.

**Comment by tshiamobhuda** [comment]
I'd like to work on this :smile: :smiley:
