### ISSUE TITLE
Edit Email optin Thank you page

### ISSUE THREAD

**Issue by gayankalhara** [gayankalhara/reallybadgifts-coming-soon#3]
![rbg landing page pls confirm](https://user-images.githubusercontent.com/8076584/32116703-5b267456-bb69-11e7-8c20-0def3ba3b324.png)

**Comment by AshiSinha18** [comment]
may i work on it?

**Comment by gayankalhara** [comment]
@AshiSinha18 Sure... Here's the transparent PNG of the character.

![char-2](https://user-images.githubusercontent.com/8076584/32118355-f961262a-bb6e-11e7-9692-9562cb25c39f.png)

Thank you!

**Comment by tshiamobhuda** [comment]
i'd like to work on this :smile:
