### ISSUE TITLE
tos.html is not matching with the home page styles

### ISSUE THREAD

**Issue by gayankalhara** [gayankalhara/reallybadgifts-coming-soon#8]
tos.html looks very plain and doesn't match with main page styles. Please adjust CSS of that one.

**Comment by Duran914** [comment]
I like to help out on this

**Comment by gayankalhara** [comment]
Thanks @Duran914 
Your help is highly appreciated...

**Comment by tshiamobhuda** [comment]
Hey, id like to help out :smile:

**Comment by tshiamobhuda** [comment]
i'd like to help @gayankalhara

**Comment by gayankalhara** [comment]
@tshiamobhuda The issue was already resolved... Please check other issues.

Thanks!
